"""a

Revision ID: a7f81102b805
Revises: 
Create Date: 2022-01-27 22:23:06.568598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f81102b805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('contactNumber', sa.String(), nullable=False))
    op.drop_constraint('User_emailPhone_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['contactNumber'])
    op.drop_column('User', 'emailPhone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('emailPhone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_emailPhone_key', 'User', ['emailPhone'])
    op.drop_column('User', 'contactNumber')
    # ### end Alembic commands ###
